Rauf Gaming Web/Controllers/BuyController.cs
using Rauf_Gaming.Classes;
using Rauf_Gaming.Models;
using Rauf_Gaming_Web.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rauf_Gaming_Web.Controllers
{
    public class BuyController : Controller
    {
        // GET: Buy
        public ActionResult CheckOut()
        {
            if (Session["MyCart"] != null)
            {
                List<CartProduct> list = Session["MyCart"] as List<CartProduct>;
                if (list.Count == 0)
                {
                    Session["Total"] = null;
                    return RedirectToAction("Shop", "Game");
                }
                return View();
            }
            else
            {
                return RedirectToAction("Shop", "Game");
            }

        }
        public ActionResult MyCart()
        {
            if (Session["MyCart"] != null)
            {
                List<CartProduct> list = Session["MyCart"] as List<CartProduct>;
                if (list.Count == 0)
                {
                    Session["Total"] = null;
                    return RedirectToAction("Shop", "Game");
                }

                return View(list);
            }
            else
            {
                return RedirectToAction("Shop", "Game");
            }

        }

        [HttpPost]
        public JsonResult GetProduct(int Id)
        {
            ProductV1 product = new ProductV1();
            product = new Games().GetProductList().Where(g => g.ProductId == Id).FirstOrDefault();
            return Json(product, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult UpdateCartItem(string Id, string type, double Qty)
        {
            List<CartProduct> cart = Session["MyCart"] as List<CartProduct>;
            var obj = cart.FirstOrDefault(x => x.Id == Id && x.Type == type);
            if (obj != null)
            {
                obj.Quantity = Qty;
                obj.Total = obj.Price * Qty;
            }
            Session["MyCart"] = cart;
            return Json("true", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult AddItemToCart(CartProduct product)
        {
            List<CartProduct> cart;
            int _Total = 0;
            try
            {
                if (Session["MyCart"] != null)
                {
                    cart = Session["MyCart"] as List<CartProduct>;
                    var FindProduct = cart.Where(p => p.Id == product.Id && p.Type == product.Type).FirstOrDefault();
                    if (FindProduct != null)
                    {
                        double Qty = FindProduct.Quantity;
                        cart.Remove(FindProduct);
                        cart.Add(new CartProduct
                        {
                            Id = product.Id,
                            Name = product.Name,
                            Photo = product.Photo,
                            Price = product.Price,
                            Quantity = product.Quantity + Qty,
                            Total = (product.Quantity + Qty) * product.Price,
                            Type = product.Type
                        });


                    }
                    else
                    {
                        cart.Add(new CartProduct
                        {
                            Id = product.Id,
                            Name = product.Name,
                            Photo = product.Photo,
                            Price = product.Price,
                            Quantity = product.Quantity,
                            Total = product.Quantity * product.Price,
                            Type = product.Type
                        });
                    }
                }
                else
                {
                    cart = new List<CartProduct>();
                    cart.Add(new CartProduct
                    {
                        Id = product.Id,
                        Name = product.Name,
                        Photo = product.Photo,
                        Price = product.Price,
                        Quantity = product.Quantity,
                        Total = product.Quantity * product.Price,
                        Type = product.Type
                    });

                    Session["MyCart"] = cart;
                }
                if (cart != null)
                {
                    _Total = cart.Count;
                    Session["NoOfCartItems"] = _Total.ToString();
                }
                return Json(_Total.ToString(), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json("false", JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult RemoveProduct(int Id)
        {
            List<CartProduct> cart = Session["MyCart"] as List<CartProduct>;
            var product = cart.Where(c => c.Id == Id.ToString()).FirstOrDefault();
            cart.Remove(product);
            Session["MyCart"] = cart;
            Session["NoOfCartItems"] = cart.Count.ToString();
            return Json("Ok", JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult DoCheckOut(Order model)
        {
            try
            {
                if (Session["MyCart"] != null)
                {
                    using (var _Entity = new GamesEntities())
                    {
                        model.Date = DateTime.Now;
                        model.Status = "Pending";
                        _Entity.Entry(model).State = EntityState.Added;
                        _Entity.SaveChanges();

                        List<CartProduct> cart = Session["MyCart"] as List<CartProduct>;
                        foreach (var item in cart)
                        {
                            OrderDetail detail = new OrderDetail();
                            detail.OrderId = model.OrderId;
                            detail.Product = item.Name;
                            detail.Type = item.Type;
                            detail.Quantity = Convert.ToInt32(item.Quantity);
                            detail.UnitPrice = Convert.ToDecimal(item.Price);
                            detail.TotalPrice = Convert.ToInt32(item.Total);
                            _Entity.Entry(detail).State = EntityState.Added;
                            _Entity.SaveChanges();
                        }
                    }
                }

                Session["op"] = "true";
            }
            catch (Exception ex)
            {
                Session["op"] = "false";
            }
            return Redirect("Thanks");
        }
        public ActionResult Thanks()
        {
            return View();
        }
    }
}

Rauf Gaming Web/Views/Buy/CheckOut.cshtml
@model Rauf_Gaming.Models.Order
@{
    ViewBag.Title = "CheckOut";
}

<section class="bg-primary">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="d-flex align-items-center py-3">
                    <h2 class="h3 font-weight-semibold text-white mb-0 mr-auto">Checkout</h2>
                    <a class="btn btn-outline-light" href="/Buy/MyCart" role="button">Back to cart</a>
                </div>
            </div>
        </div>
    </div>
</section>
@using (Html.BeginForm("DoCheckOut", "Buy", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.OrderId)
    <section class="py-lg-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-9">
                    <div class="card card-default">
                        <h6 class="card-header"><i class="ya ya-pin mr-1"></i> Enter Shipping Information</h6>
                        <div class="card-body">
                            <form>
                                <div class="form-group row">
                                    <div class="col-md-6 mb-3 mb-md-0">
                                        <label for="first-name">First Name</label>
                                        @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control", @placeholder = "Enter First Name", required = "required" })
                                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })

                                    </div>
                                    <div class="col-md-6">
                                        <label for="last-name">Last Name</label>
                                        @Html.TextBoxFor(model => model.LastName, new { @class = "form-control", @placeholder = "Enter Last Name", required = "required" })
                                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-md-6">
                                        <label for="email">Email Address</label>
                                        @Html.TextBoxFor(model => model.Email, new { @class = "form-control", @placeholder = "Enter Email", required = "required" })
                                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                        <small class="form-text text-muted">We’ll never share your email with anyone else.</small>
                                    </div>
                                    <div class="col-md-6">
                                        <label for="zip">Phone</label>
                                        @Html.TextBoxFor(model => model.Phone, new { @class = "form-control", @placeholder = "Enter Phone", required = "required" })
                                        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-md-4 mb-3 mb-md-0">
                                        <label for="address">Address</label>
                                        @Html.TextBoxFor(model => model.Address, new { @class = "form-control", @placeholder = "Enter Address", required = "required" })
                                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-md-4 mb-3 mb-md-0">
                                        <label for="zip">Zip Code</label>
                                        @Html.TextBoxFor(model => model.ZipCode, new { @class = "form-control", @placeholder = "Enter Zip Code", required = "required" })
                                        @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-md-4">
                                        <label for="city">City</label>
                                        @Html.TextBoxFor(model => model.City, new { @class = "form-control", @placeholder = "Enter City", required = "required" })
                                        @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                                    </div>
                                </div>


                            </form>
                        </div>
                    </div>

                </div>
                <div class="col-lg-3">
                    <div class="card card-default mb-3">
                        <h6 class="card-header">Order Summary</h6>
                        <div class="card-body px-2">
                            <p class="font-size-md">Shipping and additional costs are calculated based on values you have entered.</p>
                            <table class="table table-striped mt-4 mb-0">
                                <tbody>
                                    @*<tr>
                                            <th scope="row">Cart Subtotal</th>
                                            <td class="text-right">$253.94</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">Shipping</th>
                                            <td class="text-right">$32.45</td>
                                        </tr>*@
                                    <tr>
                                        <th scope="row">Tax</th>
                                        <td class="text-right">TL 0.00</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Total</th>
                                        <td class="text-right">
                                            <strong class="text-danger">TL @String.Format("{0:n0}", Convert.ToInt32(@Session["Total"].ToString()))</strong>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- end .card -->
                    <div class="text-right">
                        <button type="submit" class="btn btn-primary">Submit Order</button>
                    </div>
                </div>
            </div>
        </div>
    </section>

}
<script src="~/Scripts/App/Game/jsCart.js"></script>

Rauf Gaming Web/Views/Buy/MyCart.cshtml
@model List<Rauf_Gaming_Web.Models.CartProduct>
@{
    ViewBag.Title = "MyCart";
}

<section class="bg-primary">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="d-flex align-items-center py-3">
                    <h2 class="h3 font-weight-semibold text-white mb-0 mr-auto">
                        Shopping Cart <div class="font-weight-light d-inline">(@Model.Count)</div>
                    </h2>
                    <a class="btn btn-outline-light" href="/Game/Shop" role="button">Back to shop</a>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="py-lg-5">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="table-responsive">
                    <table class="table table-striped border align-items-center table-layout-fixed">
                        <thead>
                            <tr>
                                <th class="d-none d-lg-table-cell text-center" scope="col" style="width: 150px;">Product</th>
                                <th scope="col" style="width: 450px;">Title</th>
                                <th scope="col" class="text-center" style="width: 80px;">Price</th>
                                <th scope="col" class="text-center text-nowrap" style="width: 160px;">Quantity</th>
                                <th scope="col" class="text-center" style="width: 80px;">Total</th>
                                <th scope="col" style="width: 80px;"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int _Total = 0;
                                int _RowNumber = 0;
                                foreach (var product in Model)
                                {
                                    _Total = +_Total + Convert.ToInt32(product.Total);
                                    Session["Total"] = _Total;
                                    _RowNumber += 1;
                                    var Imagepath = Rauf_Gaming_Web.Classes.Settings.IMAGE_PATH + product.Photo;
                                    <tr id="tr_@_RowNumber.ToString()">
                                        <td class="d-none d-lg-table-cell text-center">
                                            <div class="img-thumbnail rounded d-inline-block">
                                                <img class="rounded" style="height: 100px" src="@Imagepath">
                                            </div>
                                        </td>
                                        <td>
                                            <h6><a href="/Game/ProductDetail?Id=@product.Id">@product.Name</a></h6>
                                            <a class="btn btn-light btn-xs" href="#">@product.Type</a>
                                        </td>
                                        <td class="text-center">TL @String.Format("{0:n0}", @Convert.ToInt32(@product.Price))</td>
                                        <td class="text-center">
                                            <div class="input-group quantity">
                                                <div class="input-group-prepend">
                                                    <button onclick="SubQuantity(this)" id="btnSubQty_@_RowNumber.ToString()" class="btn btn-link font-size-xs minus" type="button"><i class="ya ya-minus m-0"></i></button>
                                                </div>
                                                <input type="number" id="txtQty_@_RowNumber.ToString()" class="form-control text" value="@product.Quantity" min="1" disabled>
                                                <div class="input-group-append">
                                                    <button onclick="AddQuantity(this)" id="btnAddQty_@_RowNumber.ToString()" class="btn btn-link font-size-xs plus" type="button"><i class="ya ya-plus m-0"></i></button>
                                                </div>
                                            </div>

                                            <input type="hidden" value="@product.Price" id="lblPrice_@_RowNumber.ToString()" />
                                            <input type="hidden" value="@product.Id" id="productId_@_RowNumber.ToString()" />
                                            <input type="hidden" value="@product.Type" id="productType_@_RowNumber.ToString()" />
                                        </td>
                                        <td class="text-center" id="td_@_RowNumber.ToString()">TL @String.Format("{0:n0}", @Convert.ToInt32(@product.Total))</td>
                                        <td class="text-center">
                                            <button type="button" onclick="RemoveProduct(@product.Id)" class="btn btn-link p-0" data-toggle="tooltip" title="Remove from cart"><i class="ya ya-trash"></i></button>
                                        </td>
                                    </tr>
                                }
                            }



                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="row">

            <div class="col-md-6">
                <div class="card card-default mb-0">
                    <h6 class="card-header">Order Summary</h6>
                    <div class="card-body">
                        <p>Shipping and additional costs are calculated based on values you have entered.</p>
                        <table class="table table-striped mt-4 mb-0">
                            <tbody>
                                @*<tr>
                                        <th scope="row">Cart Subtotal</th>
                                        <td class="text-right">$253.94</td>
                                    </tr>*@
                                @*<tr>
                                        <th scope="row">Shipping</th>
                                        <td class="text-right">$32.45</td>
                                    </tr>*@
                                <tr>
                                    <th scope="row">Tax</th>
                                    <td class="text-right">TL 0.00</td>
                                </tr>
                                <tr>
                                    <th scope="row">Total</th>
                                    <td class="text-right">
                                        <strong class="text-danger">TL  @String.Format("{0:n0}", Convert.ToInt32(@Session["Total"].ToString()))</strong>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- end .card -->
            </div>

            <div class="col-md-6">
                <div>
                    <h6>Bank Transfer (EFT)</h6>
                    <div>

                        <table>
                            <tbody>

                                <tr>
                                    <th>
                                        <a href="#" onclick="DisplayBank('g')" id="btnGaranti">
                                            <img id="imgGaranti" src="~/Content/img/Logos/garanti-logo.png" style="width: 100px;" />
                                        </a>
                                    </th>
                                    <th style="padding-left:20px">
                                        <a href="#" onclick="DisplayBank('z')" id="btnZiraat">
                                            <img  src="~/Content/img/Logos/Ziraat-bank-logo.png" style="width: 120px;" />
                                        </a>
                                    </th>
                                </tr>
                                <tr>
                                    <th colspan="2">
                                        <div style="padding-top:15px; display:none;" id="Ziraatbank">
                                            Ziraat Bankası
                                            <hr />
                                            Name: HÜSEYİN RAUF
                                            <br />
                                            IBAN: TR 2500 0100 1945 7231 5408 5001
                                        </div>
                                        <div style="padding-top:15px;" id="Garantibank">
                                            Garanti banka E5 şubesi
                                            <hr />
                                            Name: Hüseyin Rauf
                                            <br />
                                            IBAN: TR82 0006 2001 1510 0006 6370 20
                                        </div>
                                    </th>

                                </tr>
                            </tbody>
                        </table>

                    </div>
                </div>
                <!-- end .card -->
            </div>
        </div>
        <div class="d-md-flex align-items-start mt-2 mb-4 mb-md-4">

            <div class="d-flex d-md-block flex-column ml-md-auto">
                @*<button class="btn btn-outline mr-md-1 mb-2 mb-md-0" type="button">Update Cart</button>*@
                <a class="btn btn-primary" href="/Buy/CheckOut" role="button">Proceed to Checkout</a>
            </div>
        </div>
    </div>
</section>
<script src="~/Scripts/App/Game/jsCart.js"></script>

Rauf Gaming Web/Views/Buy/Thanks.cshtml
@{
    ViewBag.Title = "Thanks";
}

<section class="bg-image text-center py-8 px-4 px-md-0" style="background-color: rgb(37, 37, 37) !important;">
    <img class="background" src="https://img.youtube.com/vi/y3Cpetu4ke4/maxresdefault.jpg" alt="">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-12 mx-auto">
                <div style="height:100px"></div>
                <section class="pt-0 py-lg-5">
                    @{

                    }
                    @{
                        if (Session["op"] != null)
                        {
                            if (Session["op"].ToString() == "true")
                            {
                                <div class="alert alert-success mb-0 rounded-0 border-left-0 border-right-0 d-none d-md-block mb-n1 index-2">
                                    <div class="container">
                                        <i class="ya ya-alert mr-2"></i><strong>We received your order, we will contact you back soon.</strong>
                                    </div>
                                </div>
                                Session["op"] = null;
                                Session["MyCart"] = null;
                                Session["Total"] = null;
                                Session["NoOfCartItems"] = null;
                            }
                            else
                            {
                                <div class="alert alert-danger mb-0 rounded-0 border-left-0 border-right-0 d-none d-md-block mb-n1 index-2">
                                    <div class="container">
                                        <i class="ya ya-alert mr-2"></i><strong>An error occured while placing order.</strong>
                                    </div>
                                </div>
                            }


                        }
                    }


                </section>
                <a class="btn btn-primary btn-rounded btn-lg" href="/">Back to home</a>

            </div>
        </div>
    </div>
</section>